📦 scxa-marker-gene-heatmap 💬 Bugfix #181594058 – Fix cell type marker gene heatmap endpoints
ebi-gene-expression-group/atlas-components pull request #113
Opened 2022-06-16 10:32 UTC by lingyun1010

Three things fixed here:
1. Refactor the cell type marker gene heatmap data enpoint by removing cell type value parameters. This feature should go with the new [web-sc PR](https://github.com/ebi-gene-expression-group/atlas-web-single-cell/pull/257) 
2. Populate the cell type dropdown options from heatmap data
3. Load the heatmap component based on the cluster type, i.e. cell type or clusters.

2022-06-16 11:22 UTC, alfonsomunozpomer requested changes
As before, colours isn’t the right word. Please use an accurate variable name that represents its purpose.

2022-10-04 09:44 UTC, upendrakumbham commented on packages/scxa-marker-gene-heatmap/html/ClustersViewDemo.js
> +          host={`http://localhost:8080/gxa/sc/`}
is this `localhost` URL expected here?

2022-10-13 10:01 UTC, upendrakumbham commented on packages/scxa-marker-gene-heatmap/html/ClustersViewDemo.js
> +          host={`http://localhost:8080/gxa/sc/`}
Good to see.

2022-10-13 10:01 UTC, upendrakumbham submitted a review, later dismissed
All looks good to me!

2023-03-31 09:32 UTC, upendrakumbham approved these changes
ALGTM!

2023-04-18 09:59 UTC, alfonsomunozpomer approved these changes
All fine!

2023-04-18 10:01 UTC, merged