New faceted search results component
ebi-gene-expression-group/atlas-components pull request #132
Opened 2022-11-30 15:22 UTC by ke4

Changes:

- Bare initial code for the new faceted search results component

2023-06-13 13:41 UTC, alfonsomunozpomer requested changes
This looks quite good! Please have a look at the detailed comments, there are several JavaScript and React stuff that should be improved or fixed.

2023-06-13 13:41 UTC, alfonsomunozpomer commented on packages/scxa-faceted-search-results-v5/src/FilterSidebar.js
> +
Quotes and semicolon style.

2023-06-13 13:41 UTC, alfonsomunozpomer commented on packages/scxa-faceted-search-results-v5/src/FilterSidebar.js
> +    const queryParamsObject = this.state.queryParams
I’ve seen `queryParams` renamed to `queryStringObject`, `queryParamsObject` (here) or just `queryParams`. I would settle on a single name. What’s wrong with just `queryParams`?

2023-06-13 13:41 UTC, alfonsomunozpomer commented on packages/scxa-faceted-search-results-v5/src/FilterSidebar.js
> +class FilterSidebar extends React.Component {
It doesn’t seem that `FilterSidebar` is stateful. We should get rid of the state and rewrite it as a function to make that explicit.

2023-06-13 13:41 UTC, alfonsomunozpomer commented on packages/scxa-faceted-search-results-v5/src/FilterList.js
> +    }
I think that for the time being we should remove sorting. Having pagination makes it really unintuitive. As a side benefit, we can have a stateless `FilterList`.

2023-06-20 12:49 UTC, ke4 commented on packages/scxa-faceted-search-results-v5/cypress/component/CheckboxFacetGroup.cy.js
> +          .to.equal(facetTooltip)
It is the same, I was thinking to use a variable for it with a meaningful name, but it is OK for me also to not use a variable for it, as it is a simple one.

2023-07-03 12:44 UTC, ke4 commented on packages/scxa-faceted-search-results-v5/src/FacetedSearchContainer.js
> +import FilterList from "./FilterList";
Ok all of these came from WebStorm automatic import (double quotes and semicolon). I am going to fix my settings and fix the code. Thanks for the reminder ;-)

2023-07-04 10:53 UTC, ke4 commented on packages/scxa-faceted-search-results-v5/src/facetgroups/CheckboxFacetGroup.js
> +    if (checkedFacets.indexOf(`true`) !== -1) {
Thanks for that. I agree with you. Replaced it.

2023-07-05 10:55 UTC, ke4 commented on packages/scxa-faceted-search-results-v5/src/facetgroups/CheckboxFacetGroupsDefaultProps.js
> +      return { facets: facets }
Thanks for this. I applied it with a bit of modification.

2023-08-08 11:33 UTC, alfonsomunozpomer requested changes
Some style issues and a few opportunities to dry out code. Almost there!

2023-08-08 11:33 UTC, alfonsomunozpomer commented on packages/scxa-faceted-search-results-v5/package.json
> +  },
This stub script can go away, or be replaced with something more useful. If you want to use this, and want some inspiration, have a look at [our template package](https://github.com/ebi-gene-expression-group/atlas-package/blob/master/package.json#L11).

2023-08-08 11:33 UTC, alfonsomunozpomer commented on packages/scxa-faceted-search-results-v5/cypress/component/MultiselectDropdownFacetGroup.cy.js
> +import React from "react"
Single quotes here.

2023-08-08 11:33 UTC, alfonsomunozpomer commented on packages/scxa-faceted-search-results-v5/cypress/component/FilterSidebar.cy.js
> +  from "../../src/facetgroups/MultiSelectDropdownFacetGroupsDefaultProps"
Single quotes in these imports.

2023-08-08 11:33 UTC, alfonsomunozpomer commented on packages/scxa-faceted-search-results-v5/cypress/component/FilterList.cy.js
> +import React from "react"
Single quotes.

2023-10-12 10:33 UTC, alfonsomunozpomer approved these changes
Good stuff! Two minor corrections and all good.

2023-10-13 11:10 UTC, merged