📦 scxa-tsne-plot 💬 feature: Use default plot method and parameterisation from backend props
ebi-gene-expression-group/atlas-components pull request #134
Opened 2023-01-31 11:13 UTC by lingyun1010

We need to change these two methods:
- https://github.com/ebi-gene-expression-group/atlas-components/blob/9301396f596483e45946a16eb9c4cd7dd16e20af/packages/scxa-tsne-plot/src/TSnePlotView.js#L58
- https://github.com/ebi-gene-expression-group/atlas-components/blob/9301396f596483e45946a16eb9c4cd7dd16e20af/packages/scxa-tsne-plot/src/TSnePlotView.js#L80

Do not process the URL text outside of URI (e.g. https://github.com/ebi-gene-expression-group/atlas-components/blob/9301396f596483e45946a16eb9c4cd7dd16e20af/packages/scxa-tsne-plot/src/TSnePlotView.js#L67), you must use URI’s API to create the URL and the last method should always be .toString().

The endpoint for default plotTypes is provided in the PR https://github.com/ebi-gene-expression-group/atlas-web-single-cell/pull/272. I am trying to update the frontend component to apply this feature.

2023-01-31 12:16 UTC, haideriqbal requested changes
@lingyun1010 can you please provide a brief description of what this PR is implementing/fixing? Also, please update your PR to use this formatting for the title so that it's a bit clearer which package is being changed in this PR (https://github.com/ebi-gene-expression-group/atlas-components/pull/113)

2023-02-01 09:46 UTC, lingyun1010 commented
> @lingyun1010 can you please provide a brief description of what this PR is implementing/fixing? Also, please update your PR to use this formatting for the title so that it's a bit clearer which package is being changed in this PR (#113)

Yes. Thanks for the reminder. I updated it and please take a review.

2023-02-09 15:11 UTC, haideriqbal commented on packages/scxa-tsne-plot/html/Demo.js
> +          atlasUrl={`http://localhost:8080/gxa/sc/`}
Please change this to `wwwdev` so that other developers don't need to run their local setup to test this component.

2023-02-09 16:06 UTC, lingyun1010 commented on packages/scxa-tsne-plot/html/Demo.js
> +    plotType: `t-SNE`,
Yes, the json response changed. and now it is adjusted to it.

2023-03-31 00:15 UTC, haideriqbal approved these changes
LGTM!

2023-04-18 10:02 UTC, merged