Bugfix/colour by category url logic 400 error
ebi-gene-expression-group/atlas-components pull request #144
Opened 2023-10-25 10:42 UTC by lingyun1010

I fix the logic in the url fetching stage, which is more straight forward, as the `colourByCategory` is decided by the vlaue of `colourBy`

2023-10-31 10:47 UTC, ke4 requested changes
I am missing a test for the code change.
Could you please add it or please describe me why we don't need it?
Thanks

2023-10-31 10:47 UTC, ke4 commented on packages/scxa-tsne-plot/src/TSnePlotView.js
> +    const resource = !isNaN(selectedColourBy) ?
Is there a test for this code change? Thanks

2023-10-31 16:37 UTC, upendrakumbham approved these changes
ALGTM!

2023-11-01 10:27 UTC, lingyun1010 commented
> I am missing a test for the code change. Could you please add it or please describe me why we don't need it? Thanks

I have looked into this issue. The true or false logic just change the value of a variable not affect any other props or state or UI staff, so we don't have a test for this.

2023-11-01 12:04 UTC, merged