Species search cell type wheel not clickable
ebi-gene-expression-group/atlas-components pull request #154
Opened 2024-07-23 11:10 UTC by lingyun1010

In `scxa-cell-type-wheel` component, we hard-coded to make a gene heatmap search at node level 4, that's right for cell type metadata search, rather than for `species` metadata search. We need to make a condition to check if the search term is `species` or not by fetching all possible species from the `scxa-cell-type-wheel-experiment-heatmap` component.

If you want to test it locally, please remember to build a local `scxa-cell-type-wheel` package by typing `npm pack` under its directory and install with the absolute/relative directory in `scxa-cell-type-wheel-experiment-heatmap` component.

I also created a html demo page for `Mus muscuslus` search term in `scxa-cell-type-wheel` component, with altered json response, by removing the incorrect entry with `Homo sapiens`. This entry issue will be solved by data side as far as I know.

2024-07-23 15:27 UTC, upendrakumbham approved these changes
LGTM! I tested in my local, 3rd level(cell types) in the cell type wheel is clickable.

2024-07-24 10:05 UTC, ke4 requested changes
I added a small suggestion, but otherwise it looks fine with me.

2024-07-24 10:05 UTC, ke4 commented on packages/scxa-cell-type-wheel-experiment-heatmap/src/CellTypeWheelExperimentHeatmap.js
> +          throw new Error('Network response was not ok')
```suggestion
          throw new Error('Network response was not ok. Please try again later.')
```

2024-07-24 10:29 UTC, ke4 approved these changes
LGTM

2024-07-24 10:31 UTC, merged