173 overlapping names in the marker gene heat map
ebi-gene-expression-group/atlas-components pull request #176
Opened 2024-09-26 09:48 UTC by lingyun1010

2024-10-01 12:17 UTC, ke4 requested changes
Many thanks for your work.
I added some suggestions regarding comment usage and code cleaning.
Could you please consider them?
Thanks

2024-10-01 12:17 UTC, ke4 commented on packages/scxa-marker-gene-heatmap/src/MarkerGeneHeatmap.js
> +          // No need to move very long labels slightly up as we tilted and trim it for long cell types
Could you remove this comment, please?
Having less or no comment in the code is always better as the comments unfortunately getting rotten as time goes.
If somebody change the code later, but leave the comment here, then it is going to confuse a new developer. It is better to leave less opportunity for this happening.
The best comment is always a non-existent comment. ;-)
We are using version control, so you can add this comment to your commit in the description session of the commit message. It is a much better place for this kind of comments.
How to do it: https://stackoverflow.com/questions/16122234/how-to-commit-a-change-with-both-message-and-description-from-the-command-li/36427485#36427485
Thanks

2024-10-01 12:17 UTC, ke4 commented on packages/scxa-marker-gene-heatmap/src/MarkerGeneHeatmap.js
> +          y: yOffset //- Math.max(splitCellTypeLabel.length - 3, 0) * heatmapRowHeight / 2
I suspect that this comment was left here by accident. We are using version control, so we don't ned it.
Thanks

2024-10-01 12:17 UTC, ke4 commented on packages/scxa-marker-gene-heatmap/src/MarkerGeneHeatmap.js
> +          text: splitCellTypeLabel.length <= 3 ? splitCellTypeLabel.join(`<br/>`) : splitCellTypeLabel.slice(0, 3).join(`<br/>`) + `...`,
Can you extract this code please to a `const` and add a well descriptive name to it?
That way you can remove the comment 1 line above.
Thanks

2024-10-03 12:01 UTC, upendrakumbham approved these changes
LGTM!

2024-10-03 12:51 UTC, ke4 approved these changes
I have implemented my change requests ;-)

2024-10-03 12:52 UTC, merged