Make inferred cell type as default if present
ebi-gene-expression-group/atlas-components pull request #84
Opened 2021-07-26 14:53 UTC by haideriqbal

This is an old feature that somehow got removed so reverted back the relevant changes, here is the older PR https://github.com/ebi-gene-expression-group/atlas-components/pull/72. Issue explanation: https://github.com/ebi-gene-expression-group/atlas-web-single-cell/issues/181.

2021-07-27 11:29 UTC, alfonsomunozpomer requested changes
In order to be consistent with the cell type wheel we should use the following metadata fields in order:
1. Inferred cell type - ontology labels
2. Inferred cell type - authors labels
3. Cell type
4. Progenitor cell type

2021-07-27 11:29 UTC, alfonsomunozpomer commented on packages/scxa-tsne-plot/__test__/ClusterTSnePlot.test.js
> +  test(`dropdown selection text is inferred_cell_type when metadata options contain when plot is coloured by metadata`, () => {
Fix grammar, please.

2021-07-27 12:22 UTC, alfonsomunozpomer requested changes
The proper value is selected in the dropdown, but notice that the left plot doesn’t honour the setting in the initial request, which is (e.g. in the demo page):
`https://wwwdev.ebi.ac.uk/gxa/sc/json/experiments/E-MTAB-5061/tsneplot/5/clusters/variable/20?method=umap&variableType=clusters`

2021-07-28 05:39 UTC, lingyun1010 requested changes
The dropdown box is not responding if you select other options in the list.

2021-08-02 12:18 UTC, haideriqbal commented
Closing this PR as this bug was resolved in other PR on backend here https://github.com/ebi-gene-expression-group/atlas-web-single-cell/pull/186

2021-08-02 12:18 UTC, closed without merging